package com.kasirku.app.ui.theme

import androidx.compose.ui.graphics.Color

// Brand Colors
val TealPrimary = Color(0xFF0D7377)
val TealLight = Color(0xFF14A3A8)
val TealDark = Color(0xFF0A5C5F)

// Semantic Colors
val SuccessGreen = Color(0xFF22C55E)
val WarningAmber = Color(0xFFF59E0B)
val DangerRed = Color(0xFFEF4444)

// ====== LIGHT SCHEME ======
val md_light_primary = Color(0xFF00595C)
val md_light_onPrimary = Color(0xFFFFFFFF)
val md_light_primaryContainer = Color(0xFF0D7377)
val md_light_onPrimaryContainer = Color(0xFFA2F5F9)
val md_light_secondary = Color(0xFF006A62)
val md_light_onSecondary = Color(0xFFFFFFFF)
val md_light_secondaryContainer = Color(0xFF08FDEA)
val md_light_onSecondaryContainer = Color(0xFF007168)
val md_light_tertiary = Color(0xFF504F4F)
val md_light_background = Color(0xFFF7FAFA)
val md_light_onBackground = Color(0xFF181C1D)
val md_light_surface = Color(0xFFF7FAFA)
val md_light_onSurface = Color(0xFF181C1D)
val md_light_surfaceVariant = Color(0xFFE0E3E3)
val md_light_onSurfaceVariant = Color(0xFF3E4949)
val md_light_outline = Color(0xFF6E7979)
val md_light_outlineVariant = Color(0xFFBEC9C9)
val md_light_error = Color(0xFFBA1A1A)
val md_light_onError = Color(0xFFFFFFFF)
val md_light_surfaceContainerLowest = Color(0xFFFFFFFF)
val md_light_surfaceContainerLow = Color(0xFFF1F4F4)
val md_light_surfaceContainer = Color(0xFFEBEEEE)
val md_light_surfaceContainerHigh = Color(0xFFE6E9E9)
val md_light_surfaceContainerHighest = Color(0xFFE0E3E3)

// ====== DARK SCHEME ======
val md_dark_primary = Color(0xFF5EDBD9)
val md_dark_onPrimary = Color(0xFF003738)
val md_dark_primaryContainer = Color(0xFF0D7377)
val md_dark_onPrimaryContainer = Color(0xFFA2F5F9)
val md_dark_secondary = Color(0xFF45FADB)
val md_dark_onSecondary = Color(0xFF003732)
val md_dark_secondaryContainer = Color(0xFF005049)
val md_dark_onSecondaryContainer = Color(0xFF67F7E0)
val md_dark_tertiary = Color(0xFFC2C0C0)
val md_dark_background = Color(0xFF101415)
val md_dark_onBackground = Color(0xFFE0E3E3)
val md_dark_surface = Color(0xFF101415)
val md_dark_onSurface = Color(0xFFE0E3E3)
val md_dark_surfaceVariant = Color(0xFF3E4949)
val md_dark_onSurfaceVariant = Color(0xFFBEC9C9)
val md_dark_outline = Color(0xFF889393)
val md_dark_outlineVariant = Color(0xFF3E4949)
val md_dark_error = Color(0xFFFFB4AB)
val md_dark_onError = Color(0xFF690005)
val md_dark_surfaceContainerLowest = Color(0xFF0B0F0F)
val md_dark_surfaceContainerLow = Color(0xFF181C1D)
val md_dark_surfaceContainer = Color(0xFF1C2021)
val md_dark_surfaceContainerHigh = Color(0xFF262B2B)
val md_dark_surfaceContainerHighest = Color(0xFF313636)
